# Generated by Django 3.1.4 on 2020-12-22 22:42

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('idField', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('savings', models.IntegerField(blank=True, null=True)),
                ('deficit', models.IntegerField(blank=True, null=True)),
                ('cleared', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClearedClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amounts', models.IntegerField()),
                ('weeklyPays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='Accounts.client')),
            ],
        ),
        migrations.CreateModel(
            name='AmountAdded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.IntegerField()),
                ('amountSaved', models.IntegerField()),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='Accounts.client')),
            ],
        ),
    ]
