# Generated by Django 3.1.4 on 2020-12-23 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20201223_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearedclients',
            name='clearedDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
