# Generated by Django 3.1.4 on 2020-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_clearedclients_clearedred'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountadded',
            name='amountSaved',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ClientsSavings',
        ),
    ]
