# Generated by Django 3.1.4 on 2021-01-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20210115_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='redPay',
        ),
        migrations.AddField(
            model_name='client',
            name='color',
            field=models.CharField(default='blue', max_length=10),
        ),
    ]
