# Generated by Django 3.1.4 on 2021-01-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_auto_20210115_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amountadded',
            name='date_paid',
            field=models.DateField(auto_now=True),
        ),
    ]
