# Generated by Django 3.1.4 on 2021-01-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_auto_20210115_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='color',
            field=models.CharField(default='rgb(58, 58, 172)', max_length=1000),
        ),
    ]
