# Generated by Django 3.1.4 on 2021-01-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_auto_20210126_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
