# Generated by Django 3.1.4 on 2021-01-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_balancesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
