# Generated by Django 3.1.4 on 2021-01-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0015_balancesheet_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='companyworth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='balancesheet',
            name='percentgrowth',
            field=models.IntegerField(null=True),
        ),
    ]
