# Generated by Django 3.1.4 on 2020-12-23 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amountadded',
            name='amountSaved',
        ),
        migrations.CreateModel(
            name='ClientsSavings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountSaved', models.IntegerField()),
                ('date_paid', models.DateField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind', to='Accounts.client')),
            ],
        ),
    ]
