# Generated by Django 3.1.4 on 2020-12-23 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20201223_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearedclients',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 23)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='restart',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='amountadded',
            name='date_paid',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
