# Generated by Django 3.1.4 on 2021-01-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_auto_20201224_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='guarantorAddress',
            field=models.CharField(default='212, HoneyGrove, lagos', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='guarantorName',
            field=models.CharField(default='Sesan Takuro', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='guarantorPhone',
            field=models.CharField(default='0939038283', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='homeAddress',
            field=models.CharField(default='0939038283', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='0939038283', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='shopAddress',
            field=models.CharField(default='8292, Alausa, Lagos', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='work',
            field=models.CharField(default='Trader', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clearedclients',
            name='clearedRed',
            field=models.BooleanField(default=False),
        ),
    ]
